[package]
name = "mdbook-var"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = "4.5"
mdbook = "0.4"
semver = "1.0"
serde_json = "1.0"
toml = "0.8.10"
tracing = "0.1.40"
